project_id = "ijocgytumkinjhmgferk"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://ijocgytumkinjhmgferk.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[db]
port = 54322

[functions.google-ads-connect]
verify_jwt = true

[functions.google-ads-callback]
verify_jwt = false

[functions.google-ads-test]
verify_jwt = true

[functions.get-campaigns]
verify_jwt = true

[functions.get-adgroups]
verify_jwt = true

[functions.get-keywords]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.get-account-context]
verify_jwt = true

[functions.get-account-metrics]
verify_jwt = true

[functions.send-insights-emails]
verify_jwt = false